### ISSUE TITLE
Credentials parameter to constructor

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/webdavfs#1]
I find the `credentials` parameter to the constructor to be an odd interface. Would it not be simpler to have a `login` and `password` parameter?

**Comment by zopyx** [comment]
I think this is a culprit from the old WebDAV implementation that also used a `credentials` parameter. In general the credentials could be included all together with the URL. The constructor should then parse the url and derive host, username and password from the URL  internally.

**Comment by zopyx** [comment]
Changed for 0.3.0 released.
