### ISSUE TITLE
HISTORY.rst Missing from Pypi package

### ISSUE THREAD

**Issue by jerodg** [PyFilesystem/webdavfs#17]
File is missing from package on pypi causing pip install to fail.

`(test-1LL52YOQ) C:\projects\test>pipenv install fs.webdavfs
Installing fs.webdavfs...
Collecting fs.webdavfs
  Downloading https://files.pythonhosted.org/packages/ab/e4/d7f22e277368bb565846af7a1deb3dc290f22b68c196e2ee352fc3ef050d/fs.webdavfs-0.3.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\x12345\AppData\Local\Temp\pip-install-umgfofa3\fs.webdavfs\setup.py", line 22, in <module>
        with io.open('HISTORY.rst', 'r', encoding='utf8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    
    ----------------------------------------

Error:  An error occurred while installing fs.webdavfs!
Command "python setup.py egg_info" failed with error code 1 in C:\Users\x12345\AppData\Local\Temp\pip-install-umgfofa3\fs.webdavfs\

This is likely caused by a bug in fs.webdavfs. Report this to its maintainers.`

**Comment by zopyx** [comment]
I think this is obsolete.

fs.webdavfs-0.3.7 install fine using pip.
