### ISSUE TITLE
Support Subversion

### ISSUE THREAD

**Issue by jayvdb** [PyFilesystem/webdavfs#19]
Expanding on https://github.com/PyFilesystem/pyfilesystem2/issues/177#issuecomment-458803498 , ...

Subversion is one of the simplest cases of VCS as a file system, and it has inbuilt webdav, to act like a generic file server, and it explicitly has the branches as a top level directory in the FS

GitHub also exposes git repos via subversion.  See https://help.github.com/articles/support-for-subversion-clients/ , so GitHub support can be added using webdavfs.

git core also provides webdav support, but it is a bit complicated.

I believe it would be very useful to have GitHub (and subversion) listed as a file system on https://www.pyfilesystem.org/page/index-of-filesystems/ .

Historically, there were some Webdav extensions which Subversion needed, but they are probably only needed to write and do auth, and may even be standardised now.

There are a few other DVCS listed at https://en.wikipedia.org/wiki/Comparison_of_version-control_software which can be accessed via Webdav (arch & Bazaar).  In most cases a few extra tests will be sufficient for adding at least read-only support.

**Comment by zopyx** [comment]
Sorry but Subversion is of little interest and ancient.
