### ISSUE TITLE
Consider implementing an Opener

### ISSUE THREAD

**Issue by willmcgugan** [PyFilesystem/webdavfs#2]
You might want to implement an [opener](https://pyfilesystem2.readthedocs.io/en/latest/reference/opener.html) for WebDavFS. So you could do the following:

```python
from fs import open_fs
webdav_fs = open_fs('webdav://user:password@webdav.example.org')
```

**Comment by willmcgugan** [comment]
There's a new [mechanism](https://pyfilesystem2.readthedocs.io/en/latest/extension.html#opener) for defining openers in 2.0.4

**Comment by zopyx** [comment]
The opener is already implemented as part of @althonos 's PR
