### ISSUE TITLE
webdavfs reads entire file into memory

### ISSUE THREAD

**Issue by mvdbeek** [PyFilesystem/webdavfs#32]
Hey there,

we've noticed that when a WebDAV instance is created the entire file is read into memory in [_get_file_data](https://github.com/PyFilesystem/webdavfs/blob/master/webdavfs/webdavfs.py#L59-L69). Could this be refactored to happen in smaller chunks ?

Thanks for any help on this!

**Comment by bgruening** [comment]
@zopyx do you have plans to work on this or any guidance?

**Comment by davelopez** [comment]
I created #34 as a possible fix for this. The actual download of the file happens in chunks, but the `WebDAVFile.data` variable holds the full file contents in memory. The PR adds an alternative mode using temporary files to store the file contents, I hope this is a reasonable solution.

**Comment by zopyx** [comment]
Merged

**Comment by davelopez** [comment]
Thank you @zopyx!

**Comment by bgruening** [comment]
@zopyx thanks a lot for the fast turnaround.

Could we maybe have a new release with those latest changes?

**Comment by zopyx** [comment]
https://pypi.org/project/fs.webdavfs/0.4.3/

**Comment by bgruening** [comment]
Great, thanks a lot and greetings from Freiburg.

**Comment by bgruening** [comment]
@zopyx can you install the latest packeg?

I get:

```
Collecting fs.webdavfs
  Downloading fs.webdavfs-0.4.3.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-10dwvvx8/fs-webdavfs_b79363c60349469faa4c52a44f1aba5d/setup.py", line 22, in <module>
          with io.open('HISTORY.rst', 'r', encoding='utf8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

```

**Comment by zopyx** [comment]
try 0.4.3.1

**Comment by bgruening** [comment]
And that works :) Thanks again.
