### ISSUE TITLE
Test failures after PR merge

### ISSUE THREAD

**Issue by zopyx** [PyFilesystem/webdavfs#4]
@althonos 

Any chance to check this test failures after merging your PR?

https://travis-ci.org/PyFilesystem/webdavfs/jobs/285598500

**Comment by althonos** [comment]
They seem to come from the tests I added in Pyfilesystem/Pyfilesystem2#68. Should be easy to fix.

**Comment by althonos** [comment]
Everything was fixed but the unicode path errors. It looks like the `webdav2` client breaks when supplied a unicode path.

**Comment by althonos** [comment]
@zopyx: Merging #5 ? 😃

**Comment by althonos** [comment]
I patched the code so that `webdav2` is only ever provided encoded filenames as binary, so it does not break anymore on `utf-8` input.

**Comment by zopyx** [comment]
hm...don't see any commit
