### ISSUE TITLE
Actual License

### ISSUE THREAD

**Issue by ReimarBauer** [PyFilesystem/webdavfs#7]
Hi @zopyx 

I am trying to add webdavfs to conda-forge, because I want to use it in our Mission Support System Software. 
There is a mismatch with the license in this project, it states BSD and also MIT. Which one do you prefer ;) 

setup.py  'License :: OSI Approved :: MIT License',
README: BSD

And also it would be great to add a LICENSE file.

best regards
Reimar

**Comment by zopyx** [comment]
OMG...the license shit again....will think about it and see how this works together with the pyfs2 license...in  general being as liberal aa possible

**Comment by zopyx** [comment]
Changed to MIT. Release with 0.3.1.

**Comment by ReimarBauer** [comment]
@zopyx 

Great, please change that line in the README too ;)

and we have it now on conda-forge.

```
License

This module is published under the BSD license.

This module was sponsored and financed by Andreas Jung/ZOPYX
```

**Comment by zopyx** [comment]
Fixed.
